---
- name: "Update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install apt packages"
  become: yes
  apt:
    pkg:
      - nodejs
      - npm

- name: Install pm2 package(s)
  shell: sudo npm install -g pm2

- name: "create workspace"
  shell: mkdir -p /home/ubuntu/workspace

- name: "copy files"
  copy:
    src: index.js
    dest: /home/ubuntu/workspace/

- name: "Run app"
  shell: cd /home/ubuntu/workspace && pm2 start index.js
